# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/gpt_project',
                'doc_host': 'https://nvtai040502.github.io',
                'git_url': 'https://github.com/nvtai040502/gpt_project',
                'lib_path': 'gpt_project'},
  'syms': {'gpt_project.core': {'gpt_project.core.foo': ('core.html#foo', 'gpt_project/core.py')}}}
